images:
  adservice:
    repository: docker.io/infrawave/adservice
    tag: v1.0.0
  cartservice:
    repository: docker.io/infrawave/cartservice
    tag: v1.0.0
  checkoutservice:
    repository: docker.io/infrawave/checkoutservice
    tag: v1.0.68
  currencyservice:
    repository: docker.io/infrawave/currencyservice
    tag: v1.0.0
  emailservice:
    repository: docker.io/infrawave/emailservice
    tag: v1.0.42
  frontend:
    repository: docker.io/infrawave/frontend
    tag: v1.0.74
  loadgenerator:
    repository: docker.io/infrawave/loadgenerator
    tag: v1.0.0
  paymentservice:
    repository: docker.io/infrawave/paymentservice
    tag: v1.0.0
  recommendationservice:
    repository: docker.io/infrawave/recommendationservice
    tag: v1.0.73
  shippingservice:
    repository: docker.io/infrawave/shippingservice
    tag: v1.0.0
  productcatalogservice:
    repository: docker.io/infrawave/productcatalogservice
    tag: v1.0.75
serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false
networkPolicies:
  create: false
sidecars:
  create: false
authorizationPolicies:
  create: false
opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  projectId: "PROJECT_ID"
googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false
seccompProfile:
  enable: false
  type: RuntimeDefault
securityContext:
  enable: true
adService:
  create: true
  name: adservice
cartService:
  create: true
  name: cartservice
checkoutService:
  create: true
  name: checkoutservice
currencyService:
  create: true
  name: currencyservice
emailService:
  create: true
  name: emailservice
frontend:
  create: true
  name: frontend
  externalService: false
  cymbalBranding: false
  platform: local
  singleSharedSession: false
  virtualService:
    create: false
loadGenerator:
  create: true
  name: loadgenerator
  checkFrontendInitContainer: true
paymentService:
  create: true
  name: paymentservice
recommendationService:
  create: true
  name: recommendationservice
shippingService:
  create: true
  name: shippingservice
productCatalogService:
  create: true
  name: productcatalogservice
cartDatabase:
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
shoppingAssistantService:
  create: false
  name: shoppingassistantservice
