images:
  adservice:
    repository: docker.io/infrawave/adservice
    tag: sha-e1e77bfa
  cartservice:
    repository: docker.io/infrawave/cartservice
    tag: sha-7c6e13af
  checkoutservice:
    repository: docker.io/infrawave/checkoutservice
    tag: sha-cd2c9458
  currencyservice:
    repository: docker.io/infrawave/currencyservice
    tag: sha-61b8440d
  emailservice:
    repository: docker.io/infrawave/emailservice
    tag: sha-82a29d65
  frontend:
    repository: docker.io/infrawave/frontend
    tag: v0.10.4
  loadgenerator:
    repository: docker.io/infrawave/loadgenerator
    tag: sha-21dea8d2
  paymentservice:
    repository: docker.io/infrawave/paymentservice
    tag: sha-bf69686e
  productcatalogservice:
    repository: ghcr.io/laxmikantagiri/microservices-demo/productcatalogservice
    tag: v0.10.4
  recommendationservice:
    repository: docker.io/infrawave/recommendationservice
    tag: sha-bf69686e
  shippingservice:
    repository: docker.io/infrawave/shippingservice
    tag: sha-bf69686e
serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false
networkPolicies:
  create: false
sidecars:
  create: false
authorizationPolicies:
  create: false
opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  projectId: "PROJECT_ID"
googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false
seccompProfile:
  enable: false
  type: RuntimeDefault
securityContext:
  enable: true
adService:
  create: true
  name: adservice
cartService:
  create: true
  name: cartservice
checkoutService:
  create: true
  name: checkoutservice
currencyService:
  create: true
  name: currencyservice
emailService:
  create: true
  name: emailservice
frontend:
  create: true
  name: frontend
  externalService: false
  cymbalBranding: false
  platform: local
  singleSharedSession: false
  virtualService:
    create: false
loadGenerator:
  create: true
  name: loadgenerator
  checkFrontendInitContainer: true
paymentService:
  create: true
  name: paymentservice
productCatalogService:
  create: true
  name: productcatalogservice
  extraLatency: ""
recommendationService:
  create: true
  name: recommendationservice
shippingService:
  create: true
  name: shippingservice
cartDatabase:
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
shoppingAssistantService:
  create: false
  name: shoppingassistantservice
